### ISSUE TITLE
alternative parts list

### ISSUE THREAD

**Issue by sp4rkie** [drduh/PC-Engines-APU-Router-Guide#1]
nice description!

2 years ago I setup such a machine with following parts list. MikroTik WLAN cards are superior since running Atheros chipsets. Feel free to include parts in your documentation.

1 x PC Engines apu2d4
1 x PC Engines case1d2blku
1 x PC Engines ac12veur2
1 x mSATA mini PCIE 8gb 
1 x MikroTik R11E-2HPnD, miniPCI-e card
1 x MikroTik R11E-5HACD, miniPCI-e card
4 x Delock 88395 WLAN 802.11 ac/a/b/g/n 2 dBi
4 x RP-SMA Jack Pigtail to MMCX (18cm)

seller I bought everything from:  varia-store.com

![IMG_20180912_125714](https://user-images.githubusercontent.com/3232165/76142826-8b212e80-6071-11ea-8bbf-20349ad5fce3.jpg)

**Comment by kucharskim** [comment]
@sp4rkie, am I right, that official case `case1d2blku` has only 2 holes for antennas and I see here that you have 4 antennas? Did you drill 2 additional mounting points for the antennas on the other side?

**Comment by sp4rkie** [comment]
correct! The original case has only 2 holes. When drilling the 2 additional holes take care to keep enough space between the board and the mounted antennae.

**Comment by drduh** [comment]
@sp4rkie how is the wireless performance holding up with those cards, and on what OS?

**Comment by sp4rkie** [comment]
the performance is good in my opinion. I still use 3 of these access points (exactly as shown in the picture above) distributed in my apartment.

performance test running between accesspoint and laptop (3m distance):

accesspoint hardware: APU with R11E-5HACD (name 'gwy')
accesspoint os: debian_version 10.13

laptop hardware: Thinkpad X1 Carbon (name 'why')
laptop os: debian_version 11.8

1. test


        nc -l 8000 > /dev/zero      # server started on 'why'
        nc why 8000 < /dev/zero     # client started on 'gwy' against 'why'
        iftop -B                    # started on 'why'

                          2.33GB             4.66GB            6.98GB             9.31GB       11.6GB
        └─────────────────┴──────────────────┴─────────────────┴──────────────────┴──────────────────
        why                             <=> gwy                               45.3MB  41.9MB  39.0MB

        ─────────────────────────────────────────────────────────────────────────────────────────────
        TX:             cum:   1.07MB   peak:   51.6KB               rates:   39.8KB  39.2KB  36.5KB
        RX:                    1.14GB           51.7MB                        45.2MB  41.9MB  39.0MB
        TOTAL:                 1.14GB           51.7MB                        45.3MB  41.9MB  39.0MB


2. test (opposite direction)


        nc -l 8000 < /dev/zero      # server started on 'why'
        nc why 8000 > /dev/zero     # client started on 'gwy' against 'why'
        iftop -B                    # started on 'why'

                          2.33GB             4.66GB            6.98GB             9.31GB       11.6GB
        └─────────────────┴──────────────────┴─────────────────┴──────────────────┴──────────────────
        why                             <=> gwy                               42.0MB  41.4MB  38.4MB

        ─────────────────────────────────────────────────────────────────────────────────────────────
        TX:             cum:    536MB   peak:   43.0MB               rates:   41.9MB  41.3MB  38.3MB
        RX:                    1.09MB           91.2KB                        87.2KB  85.7KB  79.6KB
        TOTAL:                  537MB           43.1MB                        42.0MB  41.4MB  38.4MB


if you want me to test something special I could do that for you
